### ISSUE TITLE
`/usr/libexec/java_home` unable to find Corretto 11

### ISSUE THREAD

**Issue by ziyiluo** [corretto/corretto-11#12] opened 2019-03-15 22:40 UTC
Thank you for taking the time to help improve OpenJDK and Corretto 11.

### Describe the bug
After installing `Corretto-11.0.2.3`, `/usr/libexec/java_home` is unable to detect it as a JDK package.

### To Reproduce
1. Install `amazon-corretto-11.0.2.9.3-macosx-x64.pkg`
2. `/usr/libexec/java_home -V`
3. Cannot see "Amazon Corretto 11".

### Expected behavior
Expect to see:
```
    11.0.2, x86_64:	"Amazon Corretto 11"	/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
```

### Platform information
Platform: MacOS High Sierra
```
openjdk version "11.0.2" 2019-01-15 LTS
OpenJDK Runtime Environment Corretto-11.0.2.9.3 (build 11.0.2+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.2.9.3 (build 11.0.2+9-LTS, mixed mode)
```

**Comment by ziyiluo** [comment] 2019-03-15 22:46
The issue is caused by the broken link `/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/MacOS/libjli.dylib`. The fix is to make the symlink point to the right relative path of `libjli.dylib`:
```
# Assume you install Amazon Corretto 11 using the pkg installer.
sudo ln -sf ../Home/lib/jli/libjli.dylib /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/MacOS/libjli.dylib
```

We will address this issue in the next release.

**Comment by ziyiluo** [comment] 2019-03-16 00:54
I'll keep this issue open until the fix is released.

**Comment by rsaddey** [comment] 2019-03-20 19:50
*That's one small step for a man, one giant leap for mankind*: This bug prevented Eclipse / STS (and possibly others) from starting giving an error Google currently has no valid fix for:
<img width="532" alt="Screen Shot 2019-03-20 at 20 43 25" src="https://user-images.githubusercontent.com/9878163/54714366-0cc23880-4b51-11e9-9511-062955f6e807.png">

It does not occur with java.net OpenJDK nor with Oracle.

Thus I suggest to roll-out this fix im a timely manner.

**Comment by ziyiluo** [comment] 2019-03-20 20:14
@rsaddey We released the fixed mac installer yesterday. Please download the latest pkg file from the [corretto download page](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html), install it and try again. Let me know if your issue still exists.

**Comment by davecurrie** [comment] 2019-03-20 20:47
Closing the issue. Please re-open if the issue is not fixed with the new mac binaries.

**Closed by davecurrie** 2019-03-20 20:47 UTC
Labels: bug

**Comment by rsaddey** [comment] 2019-03-20 20:55
> @rsaddey We released the fixed mac installer yesterday. Please download the latest pkg file from the [corretto download page](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html), install it and try again. Let me know if your issue still exists.

Yep - **all green** - working flawlessly now!

And your work-around was on-target too.

IMHO, the main problem was that Google was unable to spot this causing some unfortunate distress.

Thx for the swift fix + take care!
