### ISSUE TITLE
JAVA_HOME remains on uninstall of MSI package

### ISSUE THREAD

**Issue by J-U-B** [corretto/corretto-11#17] opened 2019-03-22 22:37 UTC
### Description
When uninstalling the **MSI** package on Windows, the variable **<code>JAVA_HOME</code>** remains with the path that now no longer exists.

### To Reproduce
* install the MSI package (with standard settings)
* uninstall the MSI

### Expected behavior
* the <code>JAVA_HOME</code> system variable should be removed
* the Coretto path should be removed from the <code>PATH</code> variable (this works) 

### Platform information
    OS: Windows 7 Enterprise
    Version: Corretto 11.0.2.9.3

### Additional context
Corretto 8.202.08.2 is affected too

**Comment by davecurrie** [comment] 2019-03-23 00:43
@J-U-B Thanks for the report, we'll take a look at it as soon as possible.

**Comment by yoroto** [comment] 2019-04-02 17:20
I've tried it on both Windows 7 and Windows 10, but cannot reproduce it. Is there anything special of the Windows machine? Are the environment variables still there after you log out and log in again?

**Comment by J-U-B** [comment] 2019-04-04 14:01
There is nothing special about the machines except the fact that they are managed by a client management solution. The installation or deinstallation is done in **unattended mode**.

For example:
`msiexec /qb /x {D5A1A022-8307-4BAD-89E0-92B9F651508E}  /liwemo %TEMP%\corretto_uninst.log`

In the meantime I have also tested this with Windows 10 pro (1809). The problem also exists here.

The variable is still set after a reboot.

**Comment by yoroto** [comment] 2019-11-12 23:52
Hi @J-U-B 

I still cannot reproduce it. While I used _msiexec_ to uninstall Corretto, it removed everything.

![Screen Shot 2019-11-12 at 3 50 23 PM](https://user-images.githubusercontent.com/2706878/68720490-40305800-0564-11ea-9f9b-271318f62ce8.png)

**Comment by davecurrie** [comment] 2020-01-03 17:45
Closing because it's not reproducible. We can re-open if a repro case comes along.

**Closed by davecurrie** 2020-01-03 17:45 UTC
Labels: bug
