### ISSUE TITLE
Corretto{8||11} for Apple M1?

### ISSUE THREAD

**Issue by brainstorm** [corretto/corretto-11#175] opened 2021-02-12 01:01 UTC
This is related to https://github.com/corretto/corretto-8/issues/42 (and equivalent issue for corretto11) with an extra ask:

```
% brew install corretto11
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask-versions and homebrew/cask).
==> New Casks
lightform
==> Updated Casks
Updated 3 casks.

==> Downloading https://corretto.aws/downloads/resources/11.0.10.9.1/amazon-corretto-11.0.10.9.1-macosx-x64.pkg
```

When working on Apple M1, the downloaded object should be aarch64, not x64... although I just realised that the official AWS downloads still don't provide an arm64 JDK for OSX (Apple Silicon)?:

https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

See the `uname`:

```
$ uname -a
Darwin mylaptop 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

As of Homebrew 3.0.0, Apple silicon is officially supported:

https://brew.sh/2021/02/05/homebrew-3.0.0/

I am aware that with Rossetta2 this should work, but I would like to have the M1 native version from AWS, thanks!

**Comment by brainstorm** [comment] 2021-02-12 01:02
Duplicate of https://github.com/corretto/corretto-11/issues/165, closing...

**Comment by brainstorm** [comment] 2021-02-12 01:42
Interesting, `./gradlew build` goes belly up on trying to determine targets bits on an Apple M1, configure/build issues need to be addressed.

Reopening, since this might be interesting for other people...

Currently the prerequisite is to [install Azul for Apple M1](https://github.com/brainstorm/dotfiles/commit/874391cc1cf12a1290a0337335f766c1459587c0), because AWS still is not shipping aarch64 JDK builds (and JDK is required to build corretto):

```
> Task :openjdksrc:build

> Task :installers:mac:tar:configureBuild FAILED
Runnable configure script is not present
Generating runnable configure script at /Users/rvalls/dev/corretto-11/installers/mac/tar/corretto-build/buildRoot/build/.configure-support/generated-configure.sh
Using autoconf at /opt/homebrew/bin/autoconf [autoconf (GNU Autoconf) 2.69]
configure: Configuration created at Fri Feb 12 12:29:27 AEDT 2021.
checking for basename... /usr/bin/basename
checking for bash... /bin/bash
checking for cat... /bin/cat
checking for chmod... /bin/chmod
checking for cmp... /usr/bin/cmp
checking for comm... /usr/bin/comm
checking for cp... /bin/cp
checking for cut... /usr/bin/cut
checking for date... /bin/date
checking for gdiff... no
checking for diff... /usr/bin/diff
checking for dirname... /usr/bin/dirname
checking for echo... /bin/echo
checking for expr... /bin/expr
checking for file... /usr/bin/file
checking for find... /usr/bin/find
checking for head... /usr/bin/head
checking for gunzip... /opt/homebrew/bin/gunzip
checking for pigz... /opt/homebrew/bin/pigz
checking for ln... /bin/ln
checking for ls... /bin/ls
checking for mkdir... /bin/mkdir
checking for mktemp... /usr/bin/mktemp
checking for mv... /bin/mv
checking for nawk... no
checking for gawk... /opt/homebrew/bin/gawk
checking for printf... /usr/bin/printf
checking for greadlink... /opt/homebrew/bin/greadlink
checking for rm... /bin/rm
checking for rmdir... /bin/rmdir
checking for sh... /bin/sh
checking for sort... /usr/bin/sort
checking for tail... /usr/bin/tail
checking for gtar... no
checking for tar... /usr/bin/tar
checking for tee... /usr/bin/tee
checking for touch... /usr/bin/touch
checking for tr... /usr/bin/tr
checking for uname... /usr/bin/uname
checking for uniq... /usr/bin/uniq
checking for wc... /usr/bin/wc
checking for which... /usr/bin/which
checking for xargs... /usr/bin/xargs
checking for gawk... gawk
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for a sed that does not truncate output... /opt/homebrew/bin/gsed
checking for cygpath... no
checking for df... /bin/df
checking for cpio... /usr/bin/cpio
checking for nice... /usr/bin/nice
checking for pandoc... no
checking build system type... arm-apple-darwin20.3.0
checking host system type... arm-apple-darwin20.3.0
checking target system type... arm-apple-darwin20.3.0
checking openjdk-build os-cpu... macosx-arm
checking openjdk-target os-cpu... macosx-arm
configure: error: It is not possible to use --with-target-bits=64 on a 32 bit system. Use proper cross-compilation instead.
/Users/rvalls/dev/corretto-11/installers/mac/tar/corretto-build/buildRoot/build/.configure-support/generated-configure.sh: line 82: 5: Bad file descriptor
configure exiting with result code 1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installers:mac:tar:configureBuild'.
> Process 'command 'bash'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 35s
11 actionable tasks: 11 executed
```

**Comment by alvdavi** [comment] 2021-02-24 19:22
Hi,

It is not expected for Corretto to build in macosx-arm. There are changes needed to the source code so it can be built for M1 devices. The port of OpenJDK into macosx-arm is currently under review. We plan to work on this one. Still closing this one as duplicate of #165

**Closed as completed by alvdavi** 2021-02-24 19:22 UTC
Labels: enhancement
